apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jib-maven-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path