apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pm-core
  annotations:
  name: pm-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pm-core
  template:
    metadata:
      labels:
        app: pm-core
    spec:
      containers:
        - image: icr.io/ibmpm/pm-core:1.0
          name: pm-core
      imagePullSecrets:
        - name: icr-registry