apiVersion: v1
kind: Service
metadata:
  labels:
    app: pm-core
  name: pm-core
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pm-core
  type: NodePort